# Generated by Django 3.2.14 on 2022-08-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=150)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=50)),
                ('company_address', models.CharField(default='', max_length=150)),
                ('profile_pic', models.ImageField(upload_to='app/images/companies')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='nomail', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(default='', max_length=150)),
                ('companyname', models.CharField(default='', max_length=150)),
                ('companyaddress', models.CharField(default='', max_length=250)),
                ('jobdescription', models.TextField(default='', max_length=500)),
                ('qualification', models.CharField(default='', max_length=150)),
                ('responsibilities', models.CharField(default='', max_length=150)),
                ('location', models.CharField(default='', max_length=200)),
                ('workmode', models.CharField(default='', max_length=150)),
                ('companywebsite', models.CharField(default='', max_length=150)),
                ('companyemail', models.CharField(default='', max_length=150)),
                ('experience', models.CharField(default='', max_length=150)),
                ('skills', models.CharField(default='', max_length=250)),
                ('salary', models.CharField(default='', max_length=100)),
                ('timing', models.CharField(default='', max_length=120)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='-', max_length=50)),
                ('lastname', models.CharField(default='-', max_length=50)),
                ('contact', models.CharField(default='', max_length=50)),
                ('min_salary', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='-', max_length=50)),
                ('city', models.CharField(default='-', max_length=50)),
                ('country', models.CharField(default='-', max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('edu', models.CharField(default='-', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('profile_pic', models.ImageField(upload_to='app/images/candidates')),
                ('exp', models.CharField(default='0', max_length=50)),
                ('job_category', models.CharField(default='-', max_length=50)),
                ('website', models.CharField(default='-', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
    ]
