# Generated by Django 3.2.14 on 2022-08-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='-', max_length=50)),
                ('lastname', models.CharField(default='-', max_length=50)),
                ('contact', models.CharField(default='', max_length=50)),
                ('min_salary', models.CharField(default='', max_length=50)),
                ('edu', models.CharField(default='-', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('resume', models.ImageField(upload_to='app/resume')),
                ('exp', models.CharField(default='0', max_length=50)),
                ('job_category', models.CharField(default='-', max_length=50)),
                ('website', models.CharField(default='-', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
